// <auto-generated />
using BulkyWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BulkyWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240228110330_EfMig")]
    partial class EfMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BulkyWeb.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 9,
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 9,
                            Name = "ScFi"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 5,
                            Name = "Motivation"
                        });
                });

            modelBuilder.Entity("BulkyWeb.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Billy Spark",
                            CategoryId = 1,
                            Description = "Praesent vitae sodales libero. Praesent molecule",
                            ISBN = "SWD9999001",
                            ImageUrl = "\\images\\Products\\pexels-ron-lach-9758163.jpg",
                            ListPrice = 99.0,
                            Price = 90.0,
                            Price100 = 80.0,
                            Price50 = 85.0,
                            Title = "Fortune of Time"
                        },
                        new
                        {
                            Id = 2,
                            Author = "David Goggins",
                            CategoryId = 2,
                            Description = "For David Goggins, childhood was a nightmare -- poverty, prejudice, and physical abuse colored his days and haunted his nights",
                            ISBN = "SWD9999002",
                            ImageUrl = "\\images\\Products\\pexels-ron-lach-9758163.jpg",
                            ListPrice = 9.9000000000000004,
                            Price = 9.0,
                            Price100 = 8.0,
                            Price50 = 8.5,
                            Title = "Can't hurt me"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Isayama Hajime",
                            CategoryId = 3,
                            Description = "In a fictional world of terror , how can freedom be defined ? ",
                            ISBN = "SWD9999002",
                            ImageUrl = "\\images\\Products\\pexels-ron-lach-9758163.jpg",
                            ListPrice = 59.0,
                            Price = 50.0,
                            Price100 = 40.0,
                            Price50 = 55.0,
                            Title = "Attack on Titan"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Thomas Pesquet",
                            CategoryId = 2,
                            Description = "Dive into his fascination , the childhood dream , from the aircraf pilote to the nation hero",
                            ISBN = "SWD9999001",
                            ImageUrl = "\\images\\Products\\pexels-ron-lach-9758163.jpg",
                            ListPrice = 29.0,
                            Price = 20.0,
                            Price100 = 10.0,
                            Price50 = 25.0,
                            Title = "Ma vie sans Gravite"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Jeremy Griffith",
                            CategoryId = 2,
                            Description = "In the conspiracies theory , what's the meaning of life",
                            ISBN = "SWD9999005",
                            ImageUrl = "\\images\\Products\\pexels-ron-lach-9758163.jpg",
                            ListPrice = 70.0,
                            Price = 79.0,
                            Price100 = 40.0,
                            Price50 = 55.0,
                            Title = "Freedom"
                        });
                });

            modelBuilder.Entity("BulkyWeb.Models.Product", b =>
                {
                    b.HasOne("BulkyWeb.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
